$scripts = $HOME/.config/hypr/scripts

bindel = , xf86audioraisevolume, exec, $scripts/Volume.sh --inc # volume up
bindel = , xf86audiolowervolume, exec, $scripts/Volume.sh --dec # volume down
bindl = , xf86AudioMicMute, exec, $scripts/Volume.sh --toggle-mic # mic mute
bindl = , xf86audiomute, exec, $scripts/Volume.sh --toggle # mute
