# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1A1D1D)
$foreground = rgb(F1EAE7)
$color0 = rgb(404344)
$color1 = rgb(0B4165)
$color2 = rgb(424644)
$color3 = rgb(2C6985)
$color4 = rgb(676E27)
$color5 = rgb(716C68)
$color6 = rgb(A1938B)
$color7 = rgb(E2D9D4)
$color8 = rgb(9E9894)
$color9 = rgb(0F5787)
$color10 = rgb(585D5B)
$color11 = rgb(3A8CB2)
$color12 = rgb(8A9234)
$color13 = rgb(97908A)
$color14 = rgb(D6C3BA)
$color15 = rgb(E2D9D4)
