# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(191424)
$foreground = rgb(F4DAAB)
$color0 = rgb(413B4D)
$color1 = rgb(3A0B03)
$color2 = rgb(072BAC)
$color3 = rgb(7F0801)
$color4 = rgb(6E4407)
$color5 = rgb(047C1C)
$color6 = rgb(A7700A)
$color7 = rgb(E7C27E)
$color8 = rgb(A18758)
$color9 = rgb(4E0F04)
$color10 = rgb(0939E6)
$color11 = rgb(AA0B02)
$color12 = rgb(935A09)
$color13 = rgb(05A525)
$color14 = rgb(DF950E)
$color15 = rgb(E7C27E)
