# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(262228)
$foreground = rgb(DAD2CA)
$color0 = rgb(4C484F)
$color1 = rgb(21162C)
$color2 = rgb(261A2E)
$color3 = rgb(21281D)
$color4 = rgb(4D3F40)
$color5 = rgb(6F5E4F)
$color6 = rgb(6F5E4F)
$color7 = rgb(C1B6AC)
$color8 = rgb(877F78)
$color9 = rgb(2C1D3B)
$color10 = rgb(33233E)
$color11 = rgb(2C3526)
$color12 = rgb(675455)
$color13 = rgb(947E69)
$color14 = rgb(947E69)
$color15 = rgb(C1B6AC)
