# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #DAD2CA
background         #262228
cursor             #867A84

active_tab_foreground     #262228
active_tab_background     #DAD2CA
inactive_tab_foreground   #DAD2CA
inactive_tab_background   #262228

active_border_color   #DAD2CA
inactive_border_color #262228
bell_border_color     #21162C

color0      #4C484F
color1		#21162C
color2		#261A2E
color3		#21281D
color4		#4D3F40
color5		#6F5E4F
color6		#6F5E4F
color7		#C1B6AC
color8		#877F78
color9		#2C1D3B
color10		#33233E
color11		#2C3526
color12		#675455
color13		#947E69
color14		#947E69
color15		#C1B6AC
