# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F1EAE7
background         #1A1D1D
cursor             #A4A3A1

active_tab_foreground     #1A1D1D
active_tab_background     #F1EAE7
inactive_tab_foreground   #F1EAE7
inactive_tab_background   #1A1D1D

active_border_color   #F1EAE7
inactive_border_color #1A1D1D
bell_border_color     #0B4165

color0      #404344
color1		#0B4165
color2		#424644
color3		#2C6985
color4		#676E27
color5		#716C68
color6		#A1938B
color7		#E2D9D4
color8		#9E9894
color9		#0F5787
color10		#585D5B
color11		#3A8CB2
color12		#8A9234
color13		#97908A
color14		#D6C3BA
color15		#E2D9D4
