# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F4DAAB
background         #191424
cursor             #7E89C8

active_tab_foreground     #191424
active_tab_background     #F4DAAB
inactive_tab_foreground   #F4DAAB
inactive_tab_background   #191424

active_border_color   #F4DAAB
inactive_border_color #191424
bell_border_color     #3A0B03

color0      #413B4D
color1		#3A0B03
color2		#072BAC
color3		#7F0801
color4		#6E4407
color5		#047C1C
color6		#A7700A
color7		#E7C27E
color8		#A18758
color9		#4E0F04
color10		#0939E6
color11		#AA0B02
color12		#935A09
color13		#05A525
color14		#DF950E
color15		#E7C27E
