# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Default Keybinds
# visit https://wiki.hyprland.org/Configuring/Binds/ for more info

# /* ---- ✴️ Variables ✴️ ---- */  #
$scriptsDir = $HOME/.config/hypr/scripts
$UserConfigs = $HOME/.config/hypr/UserConfigs
$UserScripts = $HOME/.config/hypr/UserScripts

bind = CTRL ALT, Delete, exec, hyprctl dispatch exit 0 # exit Hyprland
bind = SUPER, Q, killactive, # close active (not kill)
bind = SUPER SHIFT, Q, exec, $scriptsDir/KillActiveProcess.sh # Kill active process
#bind = CTRL ALT, L, exec, $scriptsDir/lockScreen.sh
bind = CTRL ALT, L, exec, hyprlock
bind = CTRL ALT, P, exec, $scriptsDir/Wlogout.sh # power menu
bind = SUPER SHIFT, N, exec, swaync-client -t -sw # swayNC notification panel
bind = SUPER SHIFT, E, exec, $scriptsDir/Kool_Quick_Settings.sh # Settings Menu KooL Hyprland Settings

# Master Layout
bind = SUPER CTRL, D, layoutmsg, removemaster
bind = SUPER, I, layoutmsg, addmaster
bind = SUPER, up, layoutmsg, cyclenext
bind = SUPER, K, layoutmsg, cycleprev
bind = SUPER CTRL, Return, layoutmsg, swapwithmaster

# Dwindle Layout
bind = SUPER SHIFT, I, togglesplit # only works on dwindle layout
bind = SUPER, P, pseudo, # dwindle

# Works on either layout (Master or Dwindle)
bind = SUPER, M, exec, hyprctl dispatch splitratio 0.3

# group
bind = SUPER, G, togglegroup # toggle group
bind = SUPER CTRL, tab, changegroupactive  # change focus to another window

bind = ALT, tab, cyclenext
bind = ALT, tab, bringactivetotop  

bind = , Print, exec, $HOME/.local/bin/hyprshot -m region

#swaync
bind = SUPER, tab, exec, swaync-client -t -sw


