binde = SUPER SHIFT, w, movecurrentworkspacetomonitor, u
binde = SUPER SHIFT, s, movecurrentworkspacetomonitor, d

binde = SUPER SHIFT, h, resizeactive,-50 0
binde = SUPER SHIFT, l, resizeactive,50 0
binde = SUPER SHIFT, k, resizeactive,0 -50
binde = SUPER SHIFT, j, resizeactive,0 50

bind = SUPER CTRL, h, movewindow, l
bind = SUPER CTRL, l, movewindow, r
bind = SUPER CTRL, k, movewindow, u
bind = SUPER CTRL, j, movewindow, d

bind = SUPER ALT, h, swapwindow, l
bind = SUPER ALT, l, swapwindow, r
bind = SUPER ALT, k, swapwindow, u
bind = SUPER ALT, j, swapwindow, d

bind = SUPER, h, movefocus, l
bind = SUPER, l, movefocus, r
bind = SUPER, k, movefocus, u
bind = SUPER, j, movefocus, d

bind = SUPER SHIFT, U, movetoworkspace, special
bind = SUPER, U, togglespecialworkspace,

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10

bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, 0, movetoworkspace, 10
bind = SUPER SHIFT, bracketleft, movetoworkspace, -1
bind = SUPER SHIFT, bracketright, movetoworkspace, +1

bind = SUPER CTRL, 1, movetoworkspacesilent, 1
bind = SUPER CTRL, 2, movetoworkspacesilent, 2
bind = SUPER CTRL, 3, movetoworkspacesilent, 3
bind = SUPER CTRL, 4, movetoworkspacesilent, 4
bind = SUPER CTRL, 5, movetoworkspacesilent, 5
bind = SUPER CTRL, 6, movetoworkspacesilent, 6
bind = SUPER CTRL, 7, movetoworkspacesilent, 7
bind = SUPER CTRL, 8, movetoworkspacesilent, 8
bind = SUPER CTRL, 9, movetoworkspacesilent, 9
bind = SUPER CTRL, 0, movetoworkspacesilent, 10
bind = SUPER CTRL, bracketleft, movetoworkspacesilent, -1
bind = SUPER CTRL, bracketright, movetoworkspacesilent, +1

bind = SUPER, mouse_down, workspace, e+1
bind = SUPER, mouse_up, workspace, e-1
bind = SUPER, period, workspace, e+1
bind = SUPER, comma, workspace, e-1

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
